#!/bin/bash

# Move the "macChanger" file to /usr/local/bin
sudo cp macChanger /usr/local/bin/
sudo cp macChanger.py /usr/local/bin

# Make the "macChanger" file executable
sudo chmod +x /usr/local/bin/macChanger

